# TCL File Generated by Component Editor 11.1sp2
# Mon May 19 11:24:25 COT 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | gpu "gpu" v1.0
# | Diego Andrés González Idárraga 2014.05.19.11:24:25
# | 
# | 
# | C:/Users/admin/Desktop/GPU_v2.8/gpu_hw/gpu.vhd
# | 
# |    ./gpu.vhd syn, sim
# |    ./core/core.vhd syn, sim
# |    ./core/core_pkg.vhd syn, sim
# |    ./core/ftou16.vhd syn, sim
# |    ./core/ftou32.vhd syn, sim
# |    ./core/ftou8.vhd syn, sim
# |    ./core/portc_tristate_bridge.vhd syn, sim
# |    ./core/registers.vhd syn, sim
# |    ./core/u16tof.vhd syn, sim
# |    ./core/u32tof.vhd syn, sim
# |    ./core/u8tof.vhd syn, sim
# |    ./core/pfloat/add_sub.vhd syn, sim
# |    ./core/pfloat/div.vhd syn, sim
# |    ./core/pfloat/fadd_fsub.vhd syn, sim
# |    ./core/pfloat/fcomp_fmin_fmax.vhd syn, sim
# |    ./core/pfloat/fdiv.vhd syn, sim
# |    ./core/pfloat/fmul.vhd syn, sim
# |    ./core/pfloat/fmulp2.vhd syn, sim
# |    ./core/pfloat/mul.vhd syn, sim
# |    ./core/pfloat/pfloat_pkg.vhd syn, sim
# |    ./core/pfloat/trunc_round_ceil_floor.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module gpu
# | 
set_module_property NAME gpu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Diego Andrés González Idárraga"
set_module_property DISPLAY_NAME gpu
set_module_property TOP_LEVEL_HDL_FILE gpu.vhd
set_module_property TOP_LEVEL_HDL_MODULE gpu
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME gpu
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file gpu.vhd {SYNTHESIS SIMULATION}
add_file core/core.vhd {SYNTHESIS SIMULATION}
add_file core/core_pkg.vhd {SYNTHESIS SIMULATION}
add_file core/ftou16.vhd {SYNTHESIS SIMULATION}
add_file core/ftou32.vhd {SYNTHESIS SIMULATION}
add_file core/ftou8.vhd {SYNTHESIS SIMULATION}
add_file core/portc_tristate_bridge.vhd {SYNTHESIS SIMULATION}
add_file core/registers.vhd {SYNTHESIS SIMULATION}
add_file core/u16tof.vhd {SYNTHESIS SIMULATION}
add_file core/u32tof.vhd {SYNTHESIS SIMULATION}
add_file core/u8tof.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/add_sub.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/div.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/fadd_fsub.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/fcomp_fmin_fmax.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/fdiv.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/fmul.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/fmulp2.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/mul.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/pfloat_pkg.vhd {SYNTHESIS SIMULATION}
add_file core/pfloat/trunc_round_ceil_floor.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter INSTRUCTION_SLAVE_ADDRESS_WIDTH INTEGER 12
set_parameter_property INSTRUCTION_SLAVE_ADDRESS_WIDTH DEFAULT_VALUE 12
set_parameter_property INSTRUCTION_SLAVE_ADDRESS_WIDTH DISPLAY_NAME INSTRUCTION_SLAVE_ADDRESS_WIDTH
set_parameter_property INSTRUCTION_SLAVE_ADDRESS_WIDTH TYPE INTEGER
set_parameter_property INSTRUCTION_SLAVE_ADDRESS_WIDTH UNITS None
set_parameter_property INSTRUCTION_SLAVE_ADDRESS_WIDTH AFFECTS_GENERATION false
set_parameter_property INSTRUCTION_SLAVE_ADDRESS_WIDTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point control_slave
# | 
add_interface control_slave avalon end
set_interface_property control_slave addressUnits WORDS
set_interface_property control_slave associatedClock clock
set_interface_property control_slave associatedReset reset
set_interface_property control_slave bitsPerSymbol 8
set_interface_property control_slave burstOnBurstBoundariesOnly false
set_interface_property control_slave burstcountUnits WORDS
set_interface_property control_slave explicitAddressSpan 0
set_interface_property control_slave holdTime 0
set_interface_property control_slave linewrapBursts false
set_interface_property control_slave maximumPendingReadTransactions 0
set_interface_property control_slave readLatency 0
set_interface_property control_slave readWaitTime 1
set_interface_property control_slave setupTime 0
set_interface_property control_slave timingUnits Cycles
set_interface_property control_slave writeWaitTime 0

set_interface_property control_slave ENABLED true

add_interface_port control_slave avs_control_slave_read read Input 1
add_interface_port control_slave avs_control_slave_readdata readdata Output 8
add_interface_port control_slave avs_control_slave_write write Input 1
add_interface_port control_slave avs_control_slave_writedata writedata Input 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point instruction_slave
# | 
add_interface instruction_slave avalon end
set_interface_property instruction_slave addressUnits WORDS
set_interface_property instruction_slave associatedClock clock
set_interface_property instruction_slave associatedReset reset
set_interface_property instruction_slave bitsPerSymbol 8
set_interface_property instruction_slave burstOnBurstBoundariesOnly false
set_interface_property instruction_slave burstcountUnits WORDS
set_interface_property instruction_slave explicitAddressSpan 0
set_interface_property instruction_slave holdTime 0
set_interface_property instruction_slave linewrapBursts false
set_interface_property instruction_slave maximumPendingReadTransactions 0
set_interface_property instruction_slave readLatency 0
set_interface_property instruction_slave readWaitTime 1
set_interface_property instruction_slave setupTime 0
set_interface_property instruction_slave timingUnits Cycles
set_interface_property instruction_slave writeWaitTime 0

set_interface_property instruction_slave ENABLED true

add_interface_port instruction_slave avs_instruction_slave_address address Input instruction_slave_address_width
add_interface_port instruction_slave avs_instruction_slave_write write Input 1
add_interface_port instruction_slave avs_instruction_slave_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point data_master
# | 
add_interface data_master avalon start
set_interface_property data_master addressUnits SYMBOLS
set_interface_property data_master associatedClock clock
set_interface_property data_master associatedReset reset
set_interface_property data_master bitsPerSymbol 8
set_interface_property data_master burstOnBurstBoundariesOnly false
set_interface_property data_master burstcountUnits WORDS
set_interface_property data_master doStreamReads false
set_interface_property data_master doStreamWrites false
set_interface_property data_master holdTime 0
set_interface_property data_master linewrapBursts false
set_interface_property data_master maximumPendingReadTransactions 0
set_interface_property data_master readLatency 0
set_interface_property data_master readWaitTime 1
set_interface_property data_master setupTime 0
set_interface_property data_master timingUnits Cycles
set_interface_property data_master writeWaitTime 0

set_interface_property data_master ENABLED true

add_interface_port data_master avm_data_master_address address Output 32
add_interface_port data_master avm_data_master_read read Output 1
add_interface_port data_master avm_data_master_readdata readdata Input 32
add_interface_port data_master avm_data_master_write write Output 1
add_interface_port data_master avm_data_master_writedata writedata Output 32
add_interface_port data_master avm_data_master_waitrequest waitrequest Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender_0
# | 
add_interface interrupt_sender_0 interrupt end
set_interface_property interrupt_sender_0 associatedAddressablePoint control_slave
set_interface_property interrupt_sender_0 associatedClock clock
set_interface_property interrupt_sender_0 associatedReset reset

set_interface_property interrupt_sender_0 ENABLED true

add_interface_port interrupt_sender_0 ins_irq irq Output 1
# | 
# +-----------------------------------
